

[build-system]
requires = [
  "setuptools <= 70.0.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "sdc"
version = "0.0.1"
dependencies = ["numpy", "pygame", "pytest", "pyYAML", "matplotlib", "carla"]
requires-python = ">=3.7"

[tool.black]
line-length = 100
target-version = ['py37']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | 3rdparty
    | src/pyilqr
  )/
)
'''

